default_platform(:android)

platform :android do
  desc "Distribute a new build to Firebase App Distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod -t lib/main_prod.dart"
    firebase_app_distribution(
    app: ENV["APP_ID"],
    service_credentials_file: "../fastlane/firebase_service_account.json",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
    release_notes: "New build for testing ✔️🔥",
    testers: "omarbondoah62@gmail.com",
    debug: true
  )
  end
end
